services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: Junior
      - key: N8N_BASIC_AUTH_PASSWORD
        value: @IAn8n.
